---
- name: Set hostname
  hostname:
    name: "{{ nodename }}"

- name: Perform apt dist upgrade
  apt:
    autoremove: yes
    update_cache: yes
    upgrade: dist

- name: Add packages
  apt:
    pkg: "{{ apt_packages }}"
