- name: Add geth group
  group:
    name: "{{ geth_group }}"

- name: Add geth user
  user:
    name: "{{ geth_user }}"
    group: "{{ geth_group }}"

- name: Download geth ({{ geth_version }})
  unarchive:
    src: "{{ geth_url }}"
    dest: /tmp/
    remote_src: yes
    creates: /tmp/{{ geth_version }}/geth

- name: Copy geth to /usr/local/bin
  copy:
    src: /tmp/{{ geth_version }}/geth
    dest: "{{ geth_path }}"
    remote_src: yes
    mode: 0777

- name: Create geth service file
  template:
    src: geth.service
    dest: /etc/systemd/system/geth.service
    mode: 0644

- name: Ensure datadir exists
  file:
    path: "{{ datadir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"

- name: Load geth
  systemd:
    state: restarted
    daemon_reload: yes
    name: geth.service
    enabled: yes
